export const masteryStudies = [
  {
    id: "M11",
    cost: new Decimal("1e128"),
    requirement: [() => TimeStudy.masteryStudies.isBought],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: "Disable the IP 2x multiplier cap",
  },
  {
    id: "M21",
    cost: new Decimal("1e140"),
    requirement: [11],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => `Remote Antimatter Galaxy scaling starts ${formatInt(1)} later per ${formatInt(3000)} dimension boosts`,
    effect: () => player.dimensionBoosts.div(3000).floor(),
    formatEffect: value => formatPlus(value, 0),
  },
  {
    id: "M22",
    cost: new Decimal("1e140"),
    requirement: [11],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => `Remote Antimatter Galaxy scaling starts ${formatInt(1)} later per ${formatInt(7)} Tachyonic Galaxies`,
    effect: () => player.dilation.totalTachyonGalaxies.div(7).floor(),
    formatEffect: value => formatPlus(value, 0),
  },
  {
    id: "M23",
    cost: new Decimal("1e140"),
    requirement: [11],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => `Remote Antimatter Galaxy scaling starts ${formatInt(1)} later per ${formatInt(4)} Replicanti Galaxies`,
    effect: () => Replicanti.galaxies.total.div(4).floor(),
    formatEffect: value => formatPlus(value, 0),
  },
  {
    id: "M31",
    cost: new Decimal("1e165"),
    requirement: [21],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "Dimension Boosts scale by 1 less 8th Antimatter Dimension",
    effect: () => 1,
  },
  {
    id: "M32",
    cost: new Decimal("1e165"),
    requirement: [21],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "Dimension Boosts boosts Meta Dimensions at a reduced rate",
    effect: () => DimBoost.totalBoosts.plus(1).log10(),
    formatEffect: value => formatX(value, 2),
  },
  {
    id: "M33",
    cost: new Decimal("1e165"),
    requirement: [22],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "Meta-Dimension Boosts boosts Dilated Time production",
    effect: () => MetaDimensions.boost.totalBoosts.plus(1).pow(0.5),
    formatEffect: value => formatX(value, 2),
  },
  {
    id: "M34",
    cost: new Decimal("1e165"),
    requirement: [22],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "Gain more Tachyon Particles based on Antimatter Galaxies",
    effect: () => player.galaxies.plus(1).cbrt(),
    formatEffect: value => formatX(value, 2),
  },
  {
    id: "M35",
    cost: new Decimal("1e165"),
    requirement: [23],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "The Replicanti chance upgrade can go above 100%",
  },
  {
    id: "M36",
    cost: new Decimal("1e165"),
    requirement: [23],
    reqType: TS_REQUIREMENT_TYPE.AT_LEAST_ONE,
    description: () => "Remote Replicanti Galaxy scaling is 30% weaker",
    effect: () => 0.7,
  },
];
